version: "3.9"
services:

  sso-front:
    ports:
      - "2563:80"
    container_name: sso-front
    build: 
      context: ./
      dockerfile: ./front/SSOPractice/Dockerfile
      args:
        - SCRIPT=build
    depends_on:
      - sso-back
    volumes: 
      - ./configs:/etc/nginx:ro

  sso-back:
    build: ./back
    container_name: sso-back
    volumes:
      - ./configs:/app
    env_file:
      - ./back/.env
    ports:
      - "3232:3000"


